const XHS_EMOJI_MAP: Readonly<Record<string, string>> = {
  彩虹: "🌈",
  气球: "🎈",
  玫瑰: "🌹",
  合十: "🙏",
  微笑: "🙂",
  开心: "😄",
  大笑: "😆",
  笑哭: "😂",
  捂脸: "🤦",
  偷笑: "🤭",
  害羞: "😊",
  赞: "👍",
  点赞: "👍",
  鼓掌: "👏",
  爱心: "❤️",
  红色心形: "❤️",
  飞吻: "😘",
  亲亲: "😘",
  可爱: "🥰",
  酷: "😎",
  墨镜: "😎",
  惊讶: "😮",
  流泪: "😢",
  生气: "😠",
  抓狂: "😫",
  尴尬: "😅",
  汗颜: "😅",
  疑问: "❓",
  问号: "❓",
  吃瓜: "🍉",
  礼物: "🎁",
  星星: "⭐",
  闪亮: "✨",
  太阳: "☀️",
  月亮: "🌙",
  火: "🔥",
  烟花: "🎆",
  庆祝: "🎉",
  蛋糕: "🎂",
  咖啡: "☕",
  啤酒: "🍺",
  飞机: "✈️",
  相机: "📷",
  音乐: "🎵",
  话筒: "🎤",
  灯泡: "💡",
  奖杯: "🏆",
  拳头: "✊",
  加油: "💪",
  OK: "👌",
  doge: "🐶"
};

/** Converts known Xiaohongshu custom emoji placeholders to portable Unicode emoji. */
export function normalizeXhsText(value: string): string {
  return value.replace(/\[([^\[\]\r\n]+?)R\]/g, (placeholder, name: string) => {
    return XHS_EMOJI_MAP[name.trim()] ?? placeholder;
  });
}
