# 中文模块说明：从固定源码归档的 uv.lock 与固定翻译 requirements 生成带哈希的 Windows x64 wheel 锁。
param(
  [string]$SourceArchive = "",
  [string]$PythonExecutable = "",
  [string]$PythonVersion = "3.12",
  [string]$PythonPlatform = "x86_64-pc-windows-msvc"
)

$ErrorActionPreference = "Stop"
$Root = Resolve-Path (Join-Path $PSScriptRoot "..")
$ExpectedArchiveName = "xhs-downloader-afaf2fb459980fccef9eec74e304a39af2c49cab.zip"
$ExpectedArchiveBytes = 3470287
$ExpectedArchiveSha256 = "58155970bd3a246bb6bd692f6833ef4645c44a4d39c1080e93ce9c2a4d651004"
if (-not $SourceArchive) { $SourceArchive = Join-Path $Root ".package\$ExpectedArchiveName" }
$Archive = (Resolve-Path -LiteralPath $SourceArchive).Path
$ArchiveInfo = Get-Item -LiteralPath $Archive
if ($ArchiveInfo.Name -ne $ExpectedArchiveName -or $ArchiveInfo.Length -ne $ExpectedArchiveBytes) {
  throw "XHS 源码归档文件名或大小与固定来源不匹配"
}
if ((Get-FileHash -LiteralPath $Archive -Algorithm SHA256).Hash.ToLowerInvariant() -ne $ExpectedArchiveSha256) {
  throw "XHS 固定源码归档 SHA-256 校验失败"
}
if (-not (Get-Command uv -ErrorAction SilentlyContinue)) {
  throw "uv is required to regenerate XHS locks: https://docs.astral.sh/uv/"
}

if (-not $PythonExecutable) { $PythonExecutable = Join-Path $Root ".package\stage\python-312\python\python.exe" }
$Python = (Resolve-Path -LiteralPath $PythonExecutable).Path
$PythonActualVersion = (& $Python -I -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')").Trim()
if ($PythonActualVersion -ne $PythonVersion) { throw "XHS 锁文件需要 Python $PythonVersion；找到 $PythonActualVersion" }

$PackageDirectory = Join-Path $Root ".package"
New-Item -ItemType Directory -Path $PackageDirectory -Force | Out-Null
$env:UV_CACHE_DIR = Join-Path $PackageDirectory "uv-lock-cache"
$env:UV_PYTHON = $Python
$Extraction = Join-Path $PackageDirectory ("xhs-source-lock-" + [guid]::NewGuid().ToString("N"))
$TemporaryArchiveLock = Join-Path $PackageDirectory "xhs-archive.lock.partial.txt"
New-Item -ItemType Directory -Path $Extraction | Out-Null
try {
  Expand-Archive -LiteralPath $Archive -DestinationPath $Extraction
  $Source = Get-ChildItem -LiteralPath $Extraction -Directory | Where-Object { $_.Name -like "XHS-Downloader-*" } | Select-Object -First 1
  if (-not $Source -or -not (Test-Path -LiteralPath (Join-Path $Source.FullName "uv.lock"))) {
    throw "固定源码归档中缺少 XHS-Downloader 项目与 uv.lock"
  }
  $ProjectToml = Get-Content -LiteralPath (Join-Path $Source.FullName "pyproject.toml") -Raw
  if ($ProjectToml -notmatch '(?m)^version\s*=\s*"2\.7"') { throw "XHS 固定源码版本不是 2.7" }

  Write-Host "Exporting the pinned XHS uv.lock for Python $PythonVersion..." -ForegroundColor Cyan
  & uv export --project $Source.FullName --locked --format requirements.txt --no-dev --no-emit-project --no-annotate --output-file $TemporaryArchiveLock
  if ($LASTEXITCODE -ne 0) { throw "Unable to export the pinned XHS dependency lock" }
  $LockText = Get-Content -LiteralPath $TemporaryArchiveLock -Raw
  $LockText = $LockText -replace '(?m)^# This file was autogenerated by uv via the following command:$', '# Autogenerated from the hash-pinned XHS-Downloader source archive and uv.lock; do not edit by hand.'
  $LockText = $LockText -replace '(?m)^#    uv export .*$', '#    pnpm components:lock-xhs-dependencies'
  [System.IO.File]::WriteAllText((Join-Path $PSScriptRoot "xhs-archive.lock.txt"), $LockText, [System.Text.UTF8Encoding]::new($false))
  Remove-Item -LiteralPath $TemporaryArchiveLock -Force

  Write-Host "Locking the XHS translation worker for Python $PythonVersion / $PythonPlatform..." -ForegroundColor Cyan
  & uv pip compile `
    (Join-Path $PSScriptRoot "xhs-translation-requirements.txt") `
    --python-version $PythonVersion `
    --python-platform $PythonPlatform `
    --generate-hashes `
    --custom-compile-command "pnpm components:lock-xhs-dependencies" `
    --output-file (Join-Path $PSScriptRoot "xhs-translation.lock.txt") `
    --quiet
  if ($LASTEXITCODE -ne 0) { throw "Unable to generate the XHS translation dependency lock" }
  Write-Host "XHS archive and translation locks are up to date." -ForegroundColor Green
} finally {
  Remove-Item -LiteralPath $TemporaryArchiveLock -Force -ErrorAction SilentlyContinue
  Remove-Item -LiteralPath $Extraction -Recurse -Force -ErrorAction SilentlyContinue
}
